### ISSUE TITLE
Support warning messages on tests for SHOULD assertions

### ISSUE THREAD

**Issue by halindrome** [Spec-Ops/web-platform-tests#1]
Some specs have SHOULD requirements.  We need a way to say "this test passes, but you didn't support the feature"

**Comment by msporny** [comment]
Could we have a section for "optional" tests/features? So you run all the mandatory feature tests first... then you run all the optional feature tests.

**Comment by halindrome** [comment]
Sure.  Actually, the runner allows the selection of tests via various criteria.  It is sort of primitive, but I seem to have accidentally become its maintainer yesterday... so I have ideas.
