### ISSUE TITLE
Don't generate failures for "SKIPPED: No assertion for..." subtests

### ISSUE THREAD

**Issue by joanmarie** [Spec-Ops/web-platform-tests#14]
Right now, if there's no platform assertion for a subtest, a failure like the following winds up in the generated json file:

```
        {
          "name": "doc-backlink 1",
          "status": "FAIL",
          "message": "assert_false: SKIPPED: No assertion for API AXAPI expected false got true"
        }

```

Because it's a failure, it shows up as a red square in the test-results page.

The thing is, it's not a failure. Some platforms have additional, unique requirements. Examples:

* Implementing aria-modal support for AXAPI includes the requirement that background container elements are pruned from the accessibility tree. So we need an assertion that checks an element that the other platforms don't care about.
* In DPub AAM, there are four roles which have an MSAA requirement that all children have STATE_LINKED. No other platform has such a requirement stated in the spec.

As for how to solve the red-square problem, it seems that hand editing out the failure (i.e. deleted the json content quoted above), solves it. It makes the red square go away completely when there are no platforms with an entry for that subtest. And it appears that when there one platform with such an entry, the square turns yellow-orange, which is also fine with me because it's not a fail square.

Any chance that our tools could prune the "SKIPPED" failures on our behalf so hand-editing is not needed?

**Comment by halindrome** [comment]
I think this is resolved - we now do something clever.  Do you agree it is fixed @joanmarie ?

**Comment by joanmarie** [comment]
If memory serves me (which it might not, as I'm under the weather), there was some aspect of the fix I didn't care for, making hand-editing of the json file to remove those subtests preferable. But I'd have to do another test run on multiple platforms to verify that and identify what it was I didn't care for.

So.... Feel free to close this. If and when I hit the issue, I'll ping you.
