### ISSUE TITLE
Consolidating Tests

### ISSUE THREAD

**Issue by BigBlueHat** [Spec-Ops/web-platform-tests#2]
@halindrome I've gotten a repo made under the http://github.com/w3c/ where the WG can contribute to the tests more directly.

The thought is that we could use `git submodule` or similar to include them here.
https://github.com/w3c/web-annotation-tests/pull/2

Plan is to put them in a "static" space that others can pull into their dynamic (code) projects (WPT, command line bits, etc).

Hope that's OK. Happy to loop you in more if you need!

**Comment by halindrome** [comment]
OK.  Once I finish adding the "or" functionality to JSONtest.js I am going to do a pull request into the main WPT repo and go through that process.  Getting the framework into the repo will make it much easier to then start adding tests.  Reviewing and agreeing individual tests is pretty straightforward.  Adding a ton of JS is less so.

**Comment by tcole3** [comment]
Shane, Benjamin-

So, we're now starting to generate json schemas that will be required for testing. 

Based on the spreadsheet Rob started in Berlin there are about 110  features to test, most of which will require 2 schemas each – e.g., to determine if the feature (key) appears in the annotation and then to determine if it was used correctly (i.e., if the value is valid). A valid value for the key (not all values will need to be checked, but most will be) is typically a Must, while the cardinality of keys is pretty well distributed across Must, Should, and May. So as discussed in Berlin, 200+ schemas are likely.

For now, at least - Into which repo should we put these schemas for most convenient development by the WG? Would it be appropriate to put into a folder (and sub-folders) in the WG's GitHub repo for now? These may come from or at least be edited by multiple members of the WG. 

-Tim Cole

**Comment by tcole3** [comment]
Note that, as requested by Benjamin, I have also set up a separate repo for testing:

https://github.com/w3c/web-annotation-tests

All persons who have signed up for editing the web-annotation repo also have the right to do this one

Ivan

> On 25 May 2016, at 00:47, Timothy Cole t-cole3@illinois.edu wrote:
> 
> Shane, Benjamin-
> 
> So, we're now starting to generate json schemas that will be required for testing.
> 
> Based on the spreadsheet Rob started in Berlin there are about 110  features to test, most of which will require 2 schemas each – e.g., to determine if the feature (key) appears in the annotation and then to determine if it was used correctly (i.e., if the value is valid). A valid value for the key (not all values will need to be checked, but most will be) is typically a Must, while the cardinality of keys is pretty well distributed across Must, Should, and May. So as discussed in Berlin, 200+ schemas are likely.
> 
> For now, at least - Into which repo should we put these schemas for most convenient development by the WG? Would it be appropriate to put into a folder (and sub-folders) in the WG's GitHub repo for now? These may come from or at least be edited by multiple members of the WG.
> 
> -Tim Cole
> 
> From: Shane McCarron [mailto:notifications@github.com mailto:notifications@github.com]
> Sent: Sunday, May 22, 2016 10:11 AM
> To: Spec-Ops/web-platform-tests <web-platform-tests@noreply.github.com <mailto:web-platform-tests@noreply.github.com>>
> Subject: Re: [Spec-Ops/web-platform-tests] Consolidating Tests (#2)
> 
> OK. Once I finish adding the "or" functionality to JSONtest.js I am going to do a pull request into the main WPT repo and go through that process. Getting the framework into the repo will make it much easier to then start adding tests. Reviewing and agreeing individual tests is pretty straightforward. Adding a ton of JS is less so.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Spec-2DOps_web-2Dplatform-2Dtests_issues_2-23issuecomment-2D220837462&d=CwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=zjI0r-H6xRs5fYf2_jJkju6US9ijk0nLw4ns2nuwU2k&m=cgRle1vuDZXiATkug4IYqsEhcNevzOXXpDc0BDxDoso&s=PLBffDcb43sPX1QU8PZ7FAindNnj-_g3dCnwzRUL9pk&e=<image001.jpg>

---

Ivan Herman, W3C
Digital Publishing Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by BigBlueHat** [comment]
I’ve also just successfully merged in the initial content from the WPT implementation work.

We can continue to sort through the bits of how this works, but hopefully it puts the tests themselves closer to the specs in both time and space. :)

Shane, let me know how I can help tie WPT and this together more directly—and how I can help smooth out the WPT hills and mountains (via GH issues maybe)?

**Comment by halindrome** [comment]
Sorry - I am confused.  Merged what into where?

**Comment by BigBlueHat** [comment]
Sorry.

https://github.com/w3c/web-annotation-tests/pull/2 is now on master in that repo--which is meant to be the canonical tests location (at least for collaboration) for the WG.
